### ISSUE TITLE
Bug with sliced extensions

### ISSUE THREAD

**Issue by YemreGurses** [srdc/tofhir#123]
Resource: https://hl7.org/fhir/R4/Patient.html
Endpoint: 
http://localhost:8085/tofhir/fhir-definitions?q=elements&profile=https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert

onFHIR: [REDCap common data model](https://gitlab.srdc.com.tr/medic/redcap-integration-repo)
toFHIR Mapping Repo: https://gitlab.srdc.com.tr/medic/redcap-integration-mapping
Mapping: Patient mapping in erker-mapping
Path: address.extension

There is missing data on sliced extensions:
Response:
![wrong](https://github.com/srdc/tofhir/assets/33057868/43cf94a6-2e8d-490e-b8cd-b36134e21b8e)

The response that should be
![correct](https://github.com/srdc/tofhir/assets/33057868/f1725ffe-57a6-44d1-acf6-c114f38cccde)

Difference is `isArray` and `dataTypes` fields.

**Comment by sinaci** [comment]
We handle the extension in the front-end now. Hence, this issue can be closed.
