### ISSUE TITLE
FHIR R5 warnings

### ISSUE THREAD

**Issue by YemreGurses** [srdc/tofhir#171]
After switching to the FHIR R5 release, the app started to display some warnings related to tokens/keywords. Similar warnings are also present in the onfhir app.

![image](https://github.com/srdc/tofhir/assets/33057868/72080340-361d-4253-b633-65208e2f0a62)

**Comment by sinaci** [comment]
I am closing this issue because this is related with onFHIR. We use onFHIR to load and parse the standard's structuredefinitions.
