### ISSUE TITLE
Read HL7 mssages

### ISSUE THREAD

**Issue by alkarkoukly** [srdc/tofhir#177]
This is rather a question/suggestion, and not really an issue.
Does toFHIR read HL7 messages?
If so, how to identify the fields and sub-fields in the Schema?
If not, is it planned in the future?

**Comment by sinaci** [comment]
Yes, we have recently added a new option to the sourceSettings of a mapping job configuration. You can find the short info at the readme: https://github.com/srdc/tofhir?tab=readme-ov-file#fhir-server

While adding a mapping definiton into a mapping job, the resourceType and query fields are expected. That mapping is also expected to use the schema definiton of the same resourceType. Hence, standard StructureDefinition from FHIR should be available to toFHIR. This can be done either by providing the StructureDefinition files manually or by pointing to a FHIR endpoint where the StructureDefinition(s) of those resourceTypes can be found.

**Comment by sinaci** [comment]
Closing the issue as I believe the question is answered. Please reopen to discuss further.
