### ISSUE TITLE
EFK stack problem at local development

### ISSUE THREAD

**Issue by YemreGurses** [srdc/tofhir#215]
It seems after changes on the images, local execution result details are not shown by EFK during local development. 
We may update the docker compose file accordingly if required: https://github.com/srdc/tofhir/blob/main/docker/docker-compose-efk.yml

Example screen after a fully successful mapping job execution:
![image](https://github.com/user-attachments/assets/e8e4307e-2eb9-45ad-a157-5cb398732761)

**Comment by dogukan10** [comment]
I've updated tofhir-web to utilize the latest version of Kibana dashboards. Further, there was a typo in the logback.xml configuration which has been fixed now.

**Comment by YemreGurses** [comment]
Success ones seems fixed now but there is a bug related to failed ones. A mapping task failed resulting this log:

![image](https://github.com/user-attachments/assets/360c4af3-c9b0-4ee5-ba46-8048ba80401f)

However, we cannot see statistics about the failed one (procedure-mapping) in the kibana dashboard:

![image](https://github.com/user-attachments/assets/9d5eb918-2687-4c26-a9fd-bf11f04a6896)

**Comment by dogukan10** [comment]
This problem is resolved with https://github.com/srdc/tofhir/commit/7972d36269460e52ac87839a63d39789ac207d61. Could you please test it ?

**Comment by YemreGurses** [comment]
Resolved with a441c6d32defbe5e4c09ae2d5e4bf56e9f607475
