### ISSUE TITLE
Duplicate slice name in simple structure definition

### ISSUE THREAD

**Issue by YemreGurses** [srdc/tofhir#59]
Profile Url: http://localhost:8085/tofhir/fhir-definitions?q=elements&profile=https://aiccelerate.eu/fhir/StructureDefinition/AIC-LabResultWithinSurgicalWorkflow
`code.coding` is sliced. There are duplicate slices with the same name `labResultLoincCode` as its elements.

**Comment by sinaci** [comment]
I see that such duplicate definitions come from different profiles according to their inheritance stucture if the same slice name is used. In that case we need to merge (by taking a union) these restrictions in such a way that the deeper profile in the inheritance tree should override the same restriction if inherited from parent profiles.

In this example, a cardinality restriction (max = 1) is coming from AIC-LabResult, and two code binding restrictions to different valuesets (though the latter also subsumes the previous) come from AIC-LabResult and AIC-LabResultWithinSurgicalWorkflow. To resolve the issue, we need to create the definition with the cardinality restriction and taking the deepest code binding restriction which is coming from AIC-LabResultWithinSurgicalWorkflow in this case.
