### ISSUE TITLE
Make sure that FhirMappingJobResult log is printed for all the combination of error handling settings

### ISSUE THREAD

**Issue by dogukan10** [srdc/tofhir#92]
We can configure the error handling settings of a mapping job using mappingErrorHandling and sinkSettings.errorHandling options.
This gives us the following combinations:

-   continue	| continue
-   continue 	| halt
-   halt		| continue
-   halt		| halt

Further, we should test it with batch and streaming jobs. In total, it should work for the eight different use cases.

Currently, it does not work if mappingErrorHandling is set to Halt.

Finally, we should add some tests for this functionality.

**Comment by YemreGurses** [comment]
Created a new repository and tried to run a file streaming mapping job with simple patient-mapping and a csv file. Somehow, it doesn't run my job and gives this error: 

`2023-09-04_11:12:12.931 [stream execution thread for [id = f69fed7d-4ac5-4b05-a58e-2740142e4153, runId = db574629-6b9f-4592-b430-b8f66d7fe10a]] ERROR o.a.s.s.e.s.MicroBatchExecution - Query [id = f69fed7d-4ac5-4b05-a58e-2740142e4153, runId = db574629-6b9f-4592-b430-b8f66d7fe10a] terminated with error
java.lang.IllegalArgumentException: Option 'basePath' must be a directory`


Repo: [repo.zip](https://github.com/srdc/tofhir/files/12511604/repo.zip)

**Comment by Okanmercan99** [comment]
No errors were detected after thorough testing with various combinations. To pinpoint the issue, please provide specific details about the settings that produced the incorrect result.

**Comment by dogukan10** [comment]
@Okanmercan99 thanks, I'll also have a look at this issue in my spare time and let you know if I encounter any problems. Assigning the issue to me.

**Comment by dogukan10** [comment]
I've tested it on main branch on 13/09/2023 and here is the result table:

- toFHIR-engine / Batch job

| mappingErrorHandling  | sinkSettings.errorHandling |  result|
| ------------- | ------------- | ------------- | 
| continue  | continue  | OK
| continue | halt  | OK
| halt  | continue  | No FhirMappingJobResult log, only 1 mapping failure error (mapping_error) log, no log for invalid row error
| halt  | halt  | No FhirMappingJobResult log, only 1 mapping failure error (mapping_error) log, no log for invalid row error

- toFHIR-engine / Streaming job

| mappingErrorHandling  | sinkSettings.errorHandling |  result|
| ------------- | ------------- | ------------- | 
| continue  | continue  | OK
| continue | halt  | OK
| halt  | continue  | No FhirMappingJobResult log, only 1 mapping failure error (mapping_error) log, no log for invalid row error. The same error message is printed a couple of times.
| halt  | halt  | No FhirMappingJobResult log, only 1 mapping failure error (mapping_error) log, no log for invalid row error. The same error message is printed a couple of times.

@Okanmercan99 I've used the same test data which I've already shared with you. With that test data, I expect to have following FhirMappingJobResult log:

- Number of Invalid Rows: 1
- Number  of Not Mapped: 1
- Number  of Failed writes: 1
- Number  of Written FHIR resources: 7

Of course, if we have mappingErrorHanding=halt, then no resource will be generated and the mapping job will halt. In this case, we could have another field like "Number of Not Processed" or something similar to indicate that there are some rows which are not processed because of the mapping error. WDYT @suatgonul @sinaci @YemreGurses  ?

Please let me know if you can not still reproduce the cases described above, we can have a test session to discuss this.
