### ISSUE TITLE
Extend mapping execution with the option to clear Spark's checkpoint directory

### ISSUE THREAD

**Issue by suatgonul** [srdc/tofhir#93]
We can have a single configuration parameter such as clearCheckpointDirectory, which could be used to implement job and mapping level configurations to clear corresponding folders. The implementation could be as follows:

- If no valid value provided for the parameter, the executions will continue from where they were last time.
- The configuration could take comma separated values.
  - If the configuration has only one value, which is "job", checkpoint directories for all of the mappings in the job will be deleted.
  - If the configuration has other values, each value will be treated as a mapping url. Checkpoint directories of the corresponding mappings will be deleted.

Relates to #84

**Comment by sinaci** [comment]
We added an option "clearCheckpoints" to mapping job definitions especially to reset the archiving offset so that the archiving starts from scratch.

We will add all possible configuration options to README and provide examples.
